# Generated by Django 2.0.2 on 2018-03-15 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auto_20180314_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'verbose_name': 'Лот', 'verbose_name_plural': 'Лоты'},
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='finish',
            field=models.DateTimeField(verbose_name='Окончание торгов в'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(upload_to='lots/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='start',
            field=models.DateTimeField(verbose_name='Начало торгов в'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='opened', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено в'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
    ]
