# Generated by Django 2.0.2 on 2018-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_auto_20180315_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='finish',
            field=models.DateTimeField(verbose_name='Окончание торгов'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='start',
            field=models.DateTimeField(verbose_name='Начало торгов'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
